services:
  - type: web
    name: bank-system-api
    runtime: python
    plan: free
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_comptes.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: api_comptes.settings
      - key: WEB_CONCURRENCY
        value: 1
    autoDeploy: true
