# Generated by Django 6.0.4 on 2026-04-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('accountNumber', models.CharField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accountType', models.SlugField(choices=[('epargne', 'Epargne'), ('courant', 'Courant')], default='epargne')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]