# Generated by Django 6.0.4 on 2026-04-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionType', models.SlugField(choices=[('depot', 'Depot'), ('retrait', 'Retrait')], default='depot')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceBefore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balanceAfter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('state', models.SlugField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]